### ISSUE TITLE
the todo-app.tag uses getter should be get

### ISSUE THREAD

**Issue by weberan** [luisvinicius167/riotux-todo#2]
That
`self.on('update', function ( ) {
      self.todos = ritoux.getter('todos');
});`

should be

`self.on('update', function ( ) {
      self.todos = ritoux.get('todos');
});`

I am new to riotux, but this way the example works.

**Comment by luisvinicius167** [comment]
Yeah! Thanks, I'll fix that!

**Comment by luisvinicius167** [comment]
fixed :+1: thanks!
